#!/bin/bash

PERM=~/.config/bashdirbs/permanent
CUST=~/.config/bashdirbs/custom

(
	expand_globs "$PERM"
	expand_globs "$CUST"
) | sort -n |
	uniq -c |                  # count occurences.
	grep -vE '^[ ]* 1 ' |      # get the lines that are not unique.
	sed -E 's/^[ ]* [0-9]* //' # cut off the counting.
