#!/bin/bash

function bdirbs_permanent() {
	if $(test -z "$BDIRBS_HIDE_PERM"); then
		cat ~/.bashdirbs_permanent | sed "s|^~|$HOME|" | grep -v '\*'
		cat ~/.bashdirbs_permanent | sed "s|^~|$HOME|" | grep '\*' | while read x; do
			pyexpand "$x"
		done
	fi
}

bdirbs_permanent
