#!/bin/bash

PERM=~/.config/bashdirbs/permanent
CUST=~/.config/bashdirbs/custom

function main() {
	if $(test -z "$BDIRBS_HIDE_PERM"); then
		cat "$PERM" | sed "s|^~|$HOME|" | grep -v '\*'
		cat "$PERM" | sed "s|^~|$HOME|" | grep '\*' | while read x; do
			pyexpand "$x"
		done
	fi
}

main
