#!/bin/bash

#> synopsis: cded
#> type: interactive (bash).
#> comment: edit all directory bookmarks.

PERM=~/.config/bashdirbs/permanent
CUST=~/.config/bashdirbs/custom

function main() {
	if $(test -f "$CUST"); then
		vim "$CUST"
	fi
	echo permanent bookmarks:
	bdirbs_permanent
}

main
