#!/bin/bash

#> synopsis: cdls
#> type: interactive (bash).
#> comment: print the list of all directory bookmarks (not including permanent bookmarks).

function main() {
	(
		if $(test -f ~/.bashdirbs); then
			cat ~/.bashdirbs | grep -v '\*'
			cat ~/.bashdirbs | grep '\*' | while read x; do
				pyexpand "$x"
			done
		fi
		bdirbs_permanent
	) | sort | uniq
}

main
