#!/bin/bash

#> synopsis: cdls
#> type: interactive (bash).
#> comment: print the list of all directory bookmarks (not including permanent bookmarks).

PERM=~/.config/bashdirbs/permanent
CUST=~/.config/bashdirbs/custom

function main() {
	(
		bdirbs_expand "$CUST"
		bdirbs_expand "$PERM"
	) | sort | uniq
}

main
