#!/bin/bash

# program description: print the list of all directory
# bookmarks (not including permanent bookmarks).

PERM=~/.config/bashdirbs/permanent
CUST=~/.config/bashdirbs/custom

function main() {
	(
		expand_globs "$CUST"
		expand_globs "$PERM"
	) | sort | uniq
}

main
