#!/bin/bash

# program description: print the two lists of all directory 
# bookmarks (Permanent and temporary).

PERM=~/.config/bashdirbs/permanent
CUST=~/.config/bashdirbs/custom

function main() {
	echo "PERMANENT BOOKMARKS"
	expand_globs "$PERM"
	echo "CUSTOM BOOKMARKS"
	expand_globs "$CUST"
	echo "DUPLICATE BOOKMARKS"
	bdirbs_check
}

main
